MultiselectOptions
TC3005B-562-2024/React-Frontend pull request #11
Opened 2024-04-18 01:43 UTC by elyansan

Se agrega componente "MultiselectOptions" con stories para storybook.

2024-04-18 21:48 UTC, MoisesAdame requested changes

2024-04-18 21:48 UTC, MoisesAdame commented on src/components/MultiselectOptions/MultiselectOptions.css
> +input[type="checkbox"]:checked {
Cambiar esto, ya que modifica todos los `<input type=checkbox>` a nivel global.

2024-04-18 21:48 UTC, MoisesAdame commented on src/components/MultiselectOptions/MultiselectOptions.tsx
> +const MultiselectOptions: React.FC<IMultiselectOptions> = ({ isSelected, label }) => {
Tiene alguna función el prop isSelected? Si no, mejor quitarlo.

2024-04-18 21:48 UTC, MoisesAdame commented on src/components/MultiselectOptions/MultiselectOptions.tsx
> +  const [selectedOptions, setSelectedOptions] = useState({ option1: false, option2: false, option3: false });
No es necesario que tenga tantas opciones, con que se cheque si esta activo o no el checkbox es suficiente. Quitarlas, si es posible.

2024-04-18 21:48 UTC, MoisesAdame commented on src/components/MultiselectOptions/MultiselectOptions.tsx
> +    <div className="inline-block p-2 bg-white hover:bg-neutral-200">
Como estamos usando un archivo css, en este caso MultiselectOptions.css, trasladar todas las clases de tailwind a css poniendo a cada div su respectivo className utilizando notación BEM. [Aquí un artículo de como nombrar utilizando esa notación. ](https://css-tricks.com/bem-101/)

2024-04-18 21:48 UTC, MoisesAdame commented on src/components/MultiselectOptions/MultiselectOptions.tsx
> +        <input type="checkbox" name="option1" className="appearance-none bg-neutral-200 bg-check h-6 w-6 border-2 border-black rounded checked:bg-neutral-200 checked:border- focus:outline-none mr-2"
El atributo `name`, en los input fields de un forms, debería ser distinto para cada input field, cámbialo por un identificador único, puede ser el prop `label`.

2024-04-18 21:48 UTC, MoisesAdame commented on src/components/MultiselectOptions/MultiselectOptions.tsx
> +      <label className="flex items-center justify-between">
La tag de HTML `<label>` generalmente se usa para texto, no para contener cosas, mejor cámbiala por un div.

2024-04-18 21:48 UTC, MoisesAdame commented on src/components/MultiselectOptions/types.ts
> +
Evita espacios innecesarios.

2024-04-18 21:48 UTC, MoisesAdame commented on src/components/MultiselectOptions/MultiselectOptions.css
Intenta cambiar el nombre de este archivo a multiselect-options.css, ya que así se usa generalmente en css y en la notación BEM.

2024-04-18 21:48 UTC, MoisesAdame commented on src/components/MultiselectOptions/MultiselectOptions.css
> +    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath fill='%23000' d='M5.707 7.293a1 1 0 0 0-1.414 1.414l2 2a1 1 0 0 0 1.414 0l6-6a1 1
Procura utilizar el componente `<Icons>` en vez de importar una imagen, si no está el icon que necesitas, lo podemos generar.

2024-04-18 22:49 UTC, elyansan commented on src/components/MultiselectOptions/MultiselectOptions.css
> +input[type="checkbox"]:checked {
con cualquier otro nombre está bien? ej: "checkmark"?

2024-04-20 17:36 UTC, MoisesAdame approved these changes

2024-04-20 17:36 UTC, merged