A01735902 agent info
TC3005B-562-2024/React-Frontend pull request #49
Opened 2024-04-19 23:51 UTC by ErickLimAce

2024-04-20 00:49 UTC, Djmr5 requested changes
También crees que puedas cambiar la manera en la que se pasa el **Status y el topPriorityAlert**

Algo como solo pasar en los types algo como

src/components/AgentInfo/types.ts
```javascript
Status: 'ONCALL' | 'AVAILABLE' | 'DISCONNECTED';
topPriorityAlert?: 'CRITICAL' | 'MEDIUM' | 'LOW';
```

2024-04-20 00:49 UTC, Djmr5 commented on src/components/AgentInfo/AgentInfo.stories.tsx
> +    title: 'Components/agentinfo',
Podemos cambiar el nombre a PascalCase?

2024-04-20 00:49 UTC, Djmr5 commented on src/components/AgentInfo/AgentInfo.tsx
> +import { IButton } from "../Button/types";
Creo que no estas usando estos imports. Podemos borrarlos?

2024-04-20 00:49 UTC, Djmr5 commented on src/components/AgentInfo/AgentInfo.tsx
> +    <div className="">
Falta que se vea más como la card de figma con la sombra.

Podrías crear una nueva clase en un archivo _css_ y agregarla, algo como:

AgentInfo.css
```css
.agent-info {
  @apply bg-white rounded-lg drop-shadow-lg w-full;
}
```

2024-04-20 00:49 UTC, Djmr5 commented on src/components/AgentInfo/AgentInfo.tsx
> +          <p className="text-lg">Emoción: {Emotion}</p>
No se está aplicando los estilos de la linea _7_, podemos incluirlos para que el color del texto cambie?

Puedes meter un span dentro, algo como

```html
<p className="text-lg">Emoción: <span className={styles}>{Emotion}</span></p>
```

2024-04-20 00:49 UTC, Djmr5 commented on src/components/AgentInfo/types.ts
> +    topPriorityAlert?: CRITIC | MEDIUM | LOW*/
borrar?

2024-04-20 00:49 UTC, Djmr5 commented on src/components/AgentInfo/types.ts
> +        topPriorityAlert?:React.ReactElement<IIcon>
Agregar ; a todos los atributos

2024-04-22 01:41 UTC, ErickLimAce commented on src/components/AgentInfo/AgentInfo.stories.tsx
> +    title: 'Components/agentinfo',
D

2024-04-22 01:41 UTC, ErickLimAce commented on src/components/AgentInfo/AgentInfo.tsx
> +import { IButton } from "../Button/types";
D

2024-04-22 01:42 UTC, ErickLimAce commented on src/components/AgentInfo/AgentInfo.tsx
> +    <div className="">
Revisa si te gusta así o lo muevo mas.

2024-04-22 01:42 UTC, ErickLimAce commented on src/components/AgentInfo/AgentInfo.tsx
> +          <p className="text-lg">Emoción: {Emotion}</p>
D

2024-04-22 01:42 UTC, ErickLimAce commented on src/components/AgentInfo/types.ts
> +    topPriorityAlert?: CRITIC | MEDIUM | LOW*/
D

2024-04-22 01:42 UTC, ErickLimAce commented on src/components/AgentInfo/types.ts
> +        topPriorityAlert?:React.ReactElement<IIcon>
D

2024-04-22 21:25 UTC, Djmr5 approved these changes

2024-04-22 21:32 UTC, merged