AlertExpansionPanel V1
TC3005B-562-2024/React-Frontend pull request #57
Opened 2024-04-20 20:50 UTC by Carl-MM

revisar el componente solo falta que ponga el docs (no hacer merge)

2024-04-21 20:30 UTC, Djmr5 commented on src/components/AlertExpansionPanel/AlertExpansionPanel.tsx
> +const AlertExpansionPanel: React.FC<{ alerts: Array<IAlertCardProps> }> = ({ alerts }) => {
¿Crees que podamos hacer otra interface en types y utilizar esta interfaz en vez de poner ahí los props?

2024-04-21 20:48 UTC, Djmr5 requested changes
Falta agregar el componente al index de `src/components/index.ts`

2024-04-22 03:54 UTC, Carl-MM commented on src/components/AlertExpansionPanel/AlertExpansionPanel.tsx
> +const AlertExpansionPanel: React.FC<{ alerts: Array<IAlertCardProps> }> = ({ alerts }) => {
creo que ya, revisalo

2024-04-22 03:54 UTC, Carl-MM reviewed
yap

2024-04-22 17:10 UTC, merged