Versión preliminar de componente final funcionando y mejoras en funcionalidad de los otros componentes previos encargados
TC3005B-562-2024/React-Frontend pull request #63
Opened 2024-04-21 09:31 UTC by JourneyHM

Únicamente me quedo con una duda por revisar. El porcentaje actualizable del componente final funciona únicamente si se cambia la propiedad booleana del botón a nivel de objeto más no si se da click directo. No estoy del todo seguro si eso sea normal o esté bien, ya que a nivel de db más adelante al traer los datos técnicamente actualizaría el valor al nivel del objeto y no habría falla o sino se podría implementar funcionalidad para actualizar el valor  booleano a nivel de db al dar click, actualizando así el porcentaje. Pero lo sigo revisando con el tiempo restante

2024-04-21 19:00 UTC, Djmr5 commented
@JourneyHM Yo creo que esta bien, lo importante tal vez sería que cuando empezemos a usar _axios_ podríamos mandarle una función a los botones de complete para que actualizen la lista, y por su parte los botones actualicen los datos en la base de datos, pero se ve super, gracias.
@MoisesAdame ¿Tú qué opinas? ¿Hacemos de una vez esa función?

2024-04-21 19:26 UTC, Djmr5 requested changes

2024-04-21 19:26 UTC, Djmr5 commented on src/components/CompleteButton/types.ts
Aquí me hubiera gustado más que estuvieran los colores exactos

2024-04-21 19:26 UTC, Djmr5 commented on src/components/IndividualTrainingExpansionPanel/IndividualTrainingExpansionPanel.tsx
> +                <div className={`flex-1 grow font-bold text-${titleColor} mx-4 my-2`}>{title}</div>
Igual estaría bueno que usaras la librerría de classnames, y tener cuidado al construir las clases de _taliwind dinámicamente_ así, porque tailwind solo compila las clases que pongas literalmente dentro del return o si esta en la safelist de `tailwind.config.js`

2024-04-21 19:26 UTC, Djmr5 commented on src/components/IndividualTrainingExpansionPanel/types.ts
> +    titleColor: string;
Igual me gustaría que fueran colores específicos

2024-04-22 07:12 UTC, JourneyHM commented
Cambios incorporados en espera de revisión

2024-04-22 07:12 UTC, JourneyHM commented on src/components/CompleteButton/types.ts
Hecho, en espera de revisión

2024-04-22 07:15 UTC, JourneyHM commented on src/components/IndividualTrainingExpansionPanel/IndividualTrainingExpansionPanel.tsx
> +                <div className={`flex-1 grow font-bold text-${titleColor} mx-4 my-2`}>{title}</div>
Lo mejoré agregando las classnames de "colorClasses" definidas en el tsx, mejorando así hasta la estructura de divs del return. No sé si te referías a eso. Quedo pendiente cualquier cosa.

2024-04-22 07:16 UTC, JourneyHM commented on src/components/IndividualTrainingExpansionPanel/types.ts
> +    titleColor: string;
Hecho, en espera de confirmación que ahora esté bien

2024-04-22 18:34 UTC, MoisesAdame approved these changes

2024-04-22 18:34 UTC, merged