Base Página Info Agente individual funcionando
TC3005B-562-2024/React-Frontend pull request #85
Opened 2024-04-27 16:28 UTC by JourneyHM

Dejo la base de la página por si se mergea con el main para empezar a tener la base de las páginas en el front. Además de que le hice unas mejoras a mi componente IndividualTrainingExpansionPanel, ahora funciona a la perfección.

2024-04-27 23:51 UTC, Djmr5 requested changes

2024-04-27 23:51 UTC, Djmr5 commented on src/pages/Agent/Agent.tsx
> +        <br></br>
Podrías ponerle más padding  o margin en el bottom, algo como `pb-4` o `mb-4`

2024-04-27 23:51 UTC, Djmr5 commented on src/pages/Agent/Agent.tsx
> +        <br></br>
Usar `pb-2` o `mb-2`

2024-04-27 23:51 UTC, Djmr5 commented on src/pages/Agent/Agent.tsx
> +        <br></br>
Usar `pb-2` o `mb-2`

2024-04-27 23:51 UTC, Djmr5 commented on src/pages/Agent/Agent.tsx
> +import { useParams } from "react-router-dom";
Crees que puedas crear un archivos css y poner con nombre de las clases estilo [BEM](https://www.freecodecamp.org/news/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849/) ahí las clases de tailwind con el `@apply`?

2024-05-02 19:30 UTC, MoisesAdame approved these changes

2024-05-02 19:31 UTC, Djmr5 approved these changes

2024-05-02 19:31 UTC, merged